blank_issues_enabled: false
contact_links:
  - name: Check the FAQ
    url: https://github.com/srwi/EverythingToolbar/blob/develop/FAQ.md
    about: Check frequently asked questions and troubleshooting guides
