name: CSharpier check

on: [push, pull_request]

jobs:
  check_formatting:
    runs-on: windows-2025
    name: Check Formatting
    steps:
      - uses: actions/checkout@v2
      - run: |
          dotnet tool restore
          dotnet csharpier check .
