name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Install NuGet
        uses: nuget/setup-nuget@v1

      - name: Restore NuGet dependencies
        run: nuget restore

      - name: Decode certificate
        shell: bash
        run: echo ${{ secrets.PFX_CERTIFICATE_FILE }} | base64 --decode  > ./EverythingToolbar.snk

      - name: Build all
        run: MSBuild $Env:GITHUB_WORKSPACE /p:Configuration=Release

      - name: Install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "innosetup.exe"
          Start-Process -FilePath "innosetup.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -Wait

      - name: Build installer
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "Installer\Installer.iss"

      - name: Generate SHA-256 checksum
        shell: bash
        run: sha256sum Installer/output/EverythingToolbar-${{ github.ref_name }}.exe > Installer/output/EverythingToolbar-${{ github.ref_name }}.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EverythingToolbar ${{ github.ref_name }}
          path: |
            Installer/output/EverythingToolbar-${{ github.ref_name }}.exe
            Installer/output/EverythingToolbar-${{ github.ref_name }}.sha256

      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" `
            "Installer/output/EverythingToolbar-${{ github.ref_name }}.exe" `
            "Installer/output/EverythingToolbar-${{ github.ref_name }}.sha256" `
            --draft `
            --title "${{ github.ref_name }}"